Issue #33 toggle stuck on dark & Issue #16 styling toggle button
lexoskeleton/feq_dictionary_app pull request #43
Opened 2024-08-01 16:48 UTC by audreyclarkdev

I've made a lot of changes here

- Was able to fix dark and light mode working correctly with the toggle
- Rearranged some of the order of the css 
- Styled the toggle and moon  #icon
- Added dictionary favicon images and updated favicon to point to them
- Capitalized "Dictionary Web App" title
- Made the text bold inside the search input bar

#33 & #16

2024-08-01 21:47 UTC, knopgm requested changes
Add a little gap between the toggle button and the button wrapper.

2024-08-01 21:47 UTC, knopgm commented on start-here/styles/style.css
> +  background-color: #ccc;
Change these values to get a little padding to the toggle button.  I'm not sure about how much but in this image below I was pretty close:
![image](https://github.com/user-attachments/assets/514f51cf-deb4-4980-8f07-02e2d2d25bf5)

2024-08-02 00:58 UTC, audreyclarkdev commented
@knopgm and @NuraSad 
I made some changes, and I think it looks better now. :) Thanks for the comment Gabriela!

2024-08-02 11:42 UTC, knopgm commented
Great job!

2024-08-02 11:43 UTC, knopgm approved these changes

2024-08-02 12:56 UTC, lexoskeleton approved these changes
This looks great!

2024-08-02 13:11 UTC, merged